"""
High School Management System API

A super simple FastAPI application that allows students to view and sign up
for extracurricular activities at Mergington High School.
"""

from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.responses import RedirectResponse
import os
from pathlib import Path

app = FastAPI(title="Mergington High School API",
              description="API for viewing and signing up for extracurricular activities")

# Mount the static files directory
current_dir = Path(__file__).parent
app.mount("/static", StaticFiles(directory=os.path.join(Path(__file__).parent,
          "static")), name="static")

# In-memory activity database
activities = {
        "Chess Club": {
                "description": "Learn strategies and compete in chess tournaments",
                        "schedule": "Fridays, 3:30 PM - 5:00 PM",
                                "max_participants": 12,
                                        "participants": ["michael@mergington.edu", "daniel@mergington.edu"]
                                            },
                                                "Programming Class": {
                                                        "description": "Learn programming fundamentals and build software projects",
                                                                "schedule": "Tuesdays and Thursdays, 3:30 PM - 4:30 PM",
                                                                        "max_participants": 20,
                                                                                "participants": ["emma@mergington.edu", "sophia@mergington.edu"]
                                                                                    },
                                                                                        "Gym Class": {
                                                                                                "description": "Physical education and sports activities",
                                                                                                        "schedule": "Mondays, Wednesdays, Fridays, 2:00 PM - 3:00 PM",
                                                                                                                "max_participants": 30,
                                                                                                                        "participants": ["john@mergington.edu", "olivia@mergington.edu"]
                                                                                                                            },
                                                                                                                                "Soccer Team": {
                                                                                                                                        "description": "Join the school soccer team and play matches against other schools",
                                                                                                                                                "schedule": "Mondays and Thursdays, 4:00 PM - 5:30 PM",
                                                                                                                                                        "max_participants": 22,
                                                                                                                                                                "participants": ["noah@mergington.edu", "isabella@mergington.edu"]
                                                                                                                                                                    },
                                                                                                                                                                        "Swimming Club": {
                                                                                                                                                                                "description": "Practice swimming techniques and compete in local swim meets",
                                                                                                                                                                                        "schedule": "Tuesdays and Fridays, 3:00 PM - 4:30 PM",
                                                                                                                                                                                                "max_participants": 18,
                                                                                                                                                                                                        "participants": ["liam@mergington.edu", "mia@mergington.edu"]
                                                                                                                                                                                                            },
                                                                                                                                                                                                                "Art Studio": {
                                                                                                                                                                                                                        "description": "Explore drawing, painting, and sculpture in a relaxed studio environment",
                                                                                                                                                                                                                                "schedule": "Wednesdays, 3:30 PM - 5:00 PM",
                                                                                                                                                                                                                                        "max_participants": 16,
                                                                                                                                                                                                                                                "participants": ["ava@mergington.edu", "jack@mergington.edu"]
                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                        "Drama Club": {
                                                                                                                                                                                                                                                                "description": "Act in plays, practice stagecraft, and perform at school events",
                                                                                                                                                                                                                                                                        "schedule": "Tuesdays and Saturdays, 4:00 PM - 6:00 PM",
                                                                                                                                                                                                                                                                                "max_participants": 20,
                                                                                                                                                                                                                                                                                        "participants": ["charlotte@mergington.edu", "ethan@mergington.edu"]
                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                "Robotics Team": {
                                                                                                                                                                                                                                                                                                        "description": "Design and build robots for competitions and learn engineering skills",
                                                                                                                                                                                                                                                                                                                "schedule": "Mondays and Wednesdays, 4:00 PM - 6:00 PM",
                                                                                                                                                                                                                                                                                                                        "max_participants": 15,
                                                                                                                                                                                                                                                                                                                                "participants": ["sophia@mergington.edu", "oliver@mergington.edu"]
                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                        "Debate Society": {
                                                                                                                                                                                                                                                                                                                                                "description": "Develop public speaking and argumentation skills through competitive debates",
                                                                                                                                                                                                                                                                                                                                                        "schedule": "Thursdays, 3:30 PM - 5:00 PM",
                                                                                                                                                                                                                                                                                                                                                                "max_participants": 18,
                                                                                                                                                                                                                                                                                                                                                                        "participants": ["harper@mergington.edu", "mason@mergington.edu"]
                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                "Basketball Team": {
                                                                                                                                                                                                                                                                                                                                                                                        "description": "Practice team plays and compete in school basketball games",
                                                                                                                                                                                                                                                                                                                                                                                                "schedule": "Tuesdays and Fridays, 5:00 PM - 6:30 PM",
                                                                                                                                                                                                                                                                                                                                                                                                        "max_participants": 18,
                                                                                                                                                                                                                                                                                                                                                                                                                "participants": ["tyler@mergington.edu", "natalie@mergington.edu"]
                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                        "Track and Field": {
                                                                                                                                                                                                                                                                                                                                                                                                                                "description": "Train for running, jumping, and throwing events in the track and field program",
                                                                                                                                                                                                                                                                                                                                                                                                                                        "schedule": "Wednesdays and Saturdays, 4:00 PM - 6:00 PM",
                                                                                                                                                                                                                                                                                                                                                                                                                                                "max_participants": 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "participants": ["ryan@mergington.edu", "hailey@mergington.edu"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Photography Club": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "description": "Capture images, learn photo techniques, and create visual stories",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "schedule": "Mondays, 3:30 PM - 5:00 PM",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "max_participants": 14,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "participants": ["lily@mergington.edu", "aidan@mergington.edu"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Music Ensemble": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "description": "Rehearse musical pieces and perform in concerts and school events",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "schedule": "Thursdays, 4:00 PM - 6:00 PM",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "max_participants": 20,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "participants": ["madison@mergington.edu", "jackson@mergington.edu"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Science Club": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "description": "Explore science experiments, research projects, and STEM challenges",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "schedule": "Tuesdays, 3:30 PM - 5:00 PM",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "max_participants": 18,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "participants": ["emma@mergington.edu", "lucas@mergington.edu"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Mathletes": {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "description": "Solve math problems, prepare for competitions, and sharpen analytical skills",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "schedule": "Wednesdays, 4:00 PM - 5:30 PM",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "max_participants": 16,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "participants": ["isabel@mergington.edu", "caleb@mergington.edu"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
}


@app.get("/")
def root():
    return RedirectResponse(url="/static/index.html")


@app.get("/activities")
def get_activities():
    return activities


@app.post("/activities/{activity_name}/signup")
def signup_for_activity(activity_name: str, email: str):
    """Sign up a student for an activity"""
    # Validate activity exists
    if activity_name not in activities:
        raise HTTPException(status_code=404, detail="Activity not found")

    # Get the specific activity
    activity = activities[activity_name]

    #validate email is not already signed up
    if email in activity["participants"]:
        raise HTTPException(status_code=400, detail="Email already signed up for this activity")

    # Add student
    activity["participants"].append(email)
    return {"message": f"Signed up {email} for {activity_name}"}
